version: '3.0'
services:
  haste-server:
    build: .
    networks:
      - proxynet
    environment:
      - STORAGE_TYPE=memcached
      - STORAGE_HOST=memcached
      - STORAGE_PORT=11211
    ports:
      - 7777:7777

networks:
  proxynet:
